<?hh // strict
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

namespace Facebook\HackCodegen;

use function Facebook\HackCodegen\LegacyHelpers\{
    codegen_class,
    codegen_file,
    codegen_function,
    codegen_method
};

final class CodegenFileTest extends CodegenBaseTest {

  public function testAutogenerated(): void {
    $code = test_codegen_file('no_file')
      ->setDocBlock('Completely autogenerated!')
      ->addClass(
        codegen_class('AllAutogenerated')
          ->addMethod(
            codegen_method('getName')
            ->setReturnType('string')
            ->setBody('return $this->name;')
          )
      )
      ->render();

    $this->assertUnchanged($code);
  }

  public function testGenerateTopLevelFunctions(): void {
    $function = codegen_function('fun')
      ->setReturnType('int')
      ->setBody('return 0;');
    $code = test_codegen_file('no_file')
      ->addFunction($function)
      ->render();

    $this->assertUnchanged($code);
  }

  public function testPartiallyGenerated(): void {
    $code = test_codegen_file('no_file')
      ->addClass(
        codegen_class('PartiallyGenerated')
          ->addMethod(
            codegen_method('getSomething')
              ->setManualBody()
          )
      )
      ->addClass(
        codegen_class('PartiallyGeneratedLoader')
        ->setDocBlock('We can put many clases in one file!')
      )
      ->render();

    $this->assertUnchanged($code);
  }

  private function saveAutogeneratedFile(?string $fname = null): string{
    if (Str::isEmpty($fname)) {
      $fname = Filesystem::createTemporaryFile('codegen', true);
    }
    assert($fname !== null);

    test_codegen_file($fname)
      ->setDocBlock('Testing CodegenFile with autogenerated files')
      ->addClass(
        codegen_class('Demo')
          ->addMethod(codegen_method('getName')->setBody('return "Codegen";'))
      )
      ->save();

    return $fname;
  }

  private function saveManuallyWrittenFile(?string $fname = null): string {
    if (Str::isEmpty($fname)) {
      $fname = Filesystem::createTemporaryFile('codegen', true);
    }
    assert($fname !== null);

    Filesystem::writeFileIfChanged(
      $fname,
      "<?php\n".
      "// Some handwritten code"
    );
    return $fname;
  }

  private function savePartiallyGeneratedFile(
    ?string $fname = null,
    bool $extra_method = false,
  ): string {

    if (Str::isEmpty($fname)) {
      $fname = Filesystem::createTemporaryFile('codegen', true);
    }
    assert($fname !== null);

    $class = codegen_class('Demo')
      ->addMethod(
        codegen_method('getName')
          ->setBody('// manual_section_here')
          ->setManualBody()
      );

    if ($extra_method) {
      $class->addMethod(
        codegen_method('extraMethod')->setManualBody()
      );
    }

    test_codegen_file($fname)
      ->setDocBlock('Testing CodegenFile with partially generated files')
      ->addClass($class)
      ->save();

    return $fname;
  }

  public function testSaveAutogenerated(): void {
    $fname = $this->saveAutogeneratedFile();
    $this->assertUnchanged(Filesystem::readFile($fname));
  }

  public function testClobberManuallyWrittenCode(): void {
    $this->expectException(CodegenFileNoSignatureException::class);

    $fname = $this->saveManuallyWrittenFile();
    $this->saveAutogeneratedFile($fname);
  }

  public function testReSaveAutogenerated(): void {
    $fname = $this->saveAutogeneratedFile();
    $content0 = Filesystem::readFile($fname);
    $this->saveAutogeneratedFile($fname);
    $content1 = Filesystem::readFile($fname);
    $this->assertEquals($content0, $content1);
  }

  public function testSaveModifiedAutogenerated(): void {
    $this->expectException(CodegenFileBadSignatureException::class);

    $fname = $this->saveAutogeneratedFile();
    $content = Filesystem::readFile($fname);
    Filesystem::writeFile($fname, $content.'.');
    $this->saveAutogeneratedFile($fname);
  }


  public function testSavePartiallyGenerated(): void {
    $fname = $this->savePartiallyGeneratedFile();
    $content = Filesystem::readFile($fname);
    $this->assertUnchanged($content);
    $this->assertTrue(
      PartiallyGeneratedSignedSource::hasValidSignature($content)
    );
  }

  public function testReSavePartiallyGenerated(): void {
    $fname = $this->savePartiallyGeneratedFile();
    $content0 = Filesystem::readFile($fname);
    $this->savePartiallyGeneratedFile($fname);
    $content1 = Filesystem::readFile($fname);
    $this->assertEquals($content0, $content1);
  }

  public function testSaveModifiedWrongPartiallyGenerated(): void {
    $this->expectException(CodegenFileBadSignatureException::class);

    $fname = $this->savePartiallyGeneratedFile();
    $content = Filesystem::readFile($fname);
    Filesystem::writeFile($fname, $content.'.');
    $this->saveAutogeneratedFile($fname);
  }

  private function createAndModifyPartiallyGeneratedFile(): string {
    $fname = $this->savePartiallyGeneratedFile();
    $content = Filesystem::readFile($fname);

    $new_content = str_replace(
      '// manual_section_here',
      'return $this->name;',
      $content
    );
    $this->assertFalse(
      $content == $new_content,
      "The manual content wasn't replaced. Please fix the test setup!"
    );
    Filesystem::writeFile($fname, $new_content);
    return $fname;
  }

  /**
   * Test modifying a manual section and saving.
   */
  public function testSaveModifiedManualSectionPartiallyGenerated(): void {
    $fname = $this->createAndModifyPartiallyGeneratedFile();
    $this->savePartiallyGeneratedFile($fname);
    $content = Filesystem::readFile($fname);
    $this->assertTrue(strpos($content, 'this->name') !== false);
  }

  /**
   * Test modifying a manual section and changing the code generation so
   * that the generated part is different too.
   */
  public function testSaveModifyPartiallyGenerated(): void {
    $fname = $this->createAndModifyPartiallyGeneratedFile();
    $this->savePartiallyGeneratedFile($fname, true);
    $content = Filesystem::readFile($fname);
    $this->assertTrue(strpos($content, 'return $this->name;') !== false);
    $this->assertTrue(strpos($content, 'function extraMethod()') !== false);
  }

  public function testNoSignature(): void {
    $code = test_codegen_file('no_file')
      ->setIsSignedFile(false)
      ->setDocBlock('Completely autogenerated!')
      ->addClass(
        codegen_class('NoSignature')
          ->addMethod(
            codegen_method('getName')
            ->setReturnType('string')
            ->setBody('return $this->name;')
          )
      )
      ->render();

    $this->assertUnchanged($code);
  }

  public function testNamespace(): void {
    $code = test_codegen_file('no_file')
      ->setNamespace('MyNamespace')
      ->useNamespace('Another\Space')
      ->useClass('My\Space\Bar', 'bar')
      ->useFunction('My\Space\my_function', 'f')
      ->useConst('My\Space\MAX_RETRIES')
      ->addClass(
        codegen_class('Foo')
      )
      ->render();

    $this->assertUnchanged($code);
  }

  public function testStrictFile(): void {
    $code = test_codegen_file('no_file')
      ->setIsStrict(true)
      ->addClass(codegen_class('Foo'))
      ->render();

    $this->assertUnchanged($code);
  }

  public function testPhpFile(): void {
    $code = test_codegen_file('no_file')
      ->setFileType(CodegenFileType::PHP)
      ->addClass(codegen_class('Foo'))
      ->render();

    $this->assertUnchanged($code);
  }

}
